# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "test_dummy"
  s.version = "0.2.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tadman"]
  s.date = "2011-09-21"
  s.description = "Test Dummy allows you to define how to fake models automatically so that you can use dummy data for testing instead of fixtures. Dummy models are always generated using the current schema and don't need to me migrated like fixtures."
  s.email = "github@tadman.ca"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/test_dummy.rb",
    "lib/test_dummy/helper.rb",
    "lib/test_dummy/railtie.rb",
    "lib/test_dummy/test_helper.rb",
    "test/config/database.yml",
    "test/db/.gitignore",
    "test/helper.rb",
    "test/models/simple.rb",
    "test/test_test_dummy.rb",
    "test_dummy.gemspec"
  ]
  s.homepage = "http://github.com/tadman/test_dummy"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Quick test data generator and fake model maker"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

